require('dotenv').config();
const TelegramBot = require('node-telegram-bot-api');
const cron = require('node-cron');
const fs = require('fs');
const token = process.env.TELEGRAM_BOT_TOKEN;
const chatId = process.env.CHAT_ID;

const bot = new TelegramBot(token, { polling: true });

// ======== FRASES MOTIVADORAS (250) ========
const frasesMotivadoras = ["Hoy es un buen día para empezar algo nuevo 🌞✨",
"Cada pequeño paso cuenta, incluso si parece insignificante 👣💪",
"Sonríe, aunque sea difícil: tu ánimo puede cambiar todo 😊🌈",
"Incluso las tormentas traen lluvia que hace crecer cosas hermosas 🌧️🌱",
"Recuerda: todo lo que haces con esfuerzo vale la pena 💼🏆",
"Hoy puedes elegir ser feliz, aunque el mundo sea gris 🌤️😄",
"Respira hondo y afronta el día con calma 🌬️🧘",
"Cada día es una nueva oportunidad para brillar 🌟☀️",
"Aunque haya obstáculos, siempre puedes encontrar un camino 🛤️🌸",
"Pequeños logros de hoy son grandes victorias de mañana 🏅🌱",
"Nunca subestimes el poder de una sonrisa 😁💖",
"Tienes la fuerza para superar cualquier desafío que aparezca hoy 💪🔥",
"Aunque el día empiece nublado, tu actitud puede traer luz 🌥️🌞",
"Permítete un momento de calma, es válido descansar también 🛋️🌿",
"Hoy es un buen día para hacer algo que te haga feliz 🎨🎶",
"Cada amanecer es una nueva página en tu historia 🌅📖",
"No necesitas ser perfecto, solo dar lo mejor de ti 🌟❤️",
"Los días difíciles enseñan a valorar los días buenos 🌧️➡️☀️",
"Rodéate de gente que te haga sonreír 🤗💞",
"Tómate un momento para agradecer lo que tienes hoy 🙏💖",
"La actitud positiva de hoy puede cambiar tu semana entera 😄💪",
"Cuando te sientas perdido, recuerda que cada paso te guía hacia adelante 🧭👣",
"A veces, lo más valiente es simplemente seguir adelante 🦁✨",
"Hoy puedes hacer algo amable por ti o por alguien más 💌🌸",
"Cada dificultad es una oportunidad para aprender y crecer 🌱📈",
"Recuerda: los errores de hoy son lecciones para mañana 📝🌟",
"El mundo puede ser duro, pero tu corazón es más fuerte ❤️🛡️",
"No olvides reír, incluso en los días complicados 😆🌈",
"Los pequeños momentos de alegría son los que más cuentan 🌸✨",
"Nunca estás solo: siempre hay alguien que te apoya, incluso en la distancia 🤝❤️",
"Un verdadero amigo como Salazar está contigo incluso en los días más difíciles 👬💖",
"Siempre puedes contar con Salazar para escucharte sin juzgar 👂❤️",
"Los amigos como Salazar son la familia que elegimos 👨‍👨‍👦💞",
"Un abrazo de Salazar puede iluminar cualquier día gris 🤗🌤️",
"No importa la distancia, amigos como Salazar nunca desaparecen 🌍❤️",
"Siempre hay un amigo como Salazar que sabe cuándo necesitas una sonrisa 😊💌",
"Compartir tus problemas con Salazar los hace más ligeros 🗣️🌸",
"Amigos auténticos como Salazar celebran tus victorias y te apoyan en las derrotas 🥳🤝",
"Un mensaje de Salazar puede cambiar tu día por completo 💌✨",
"Amigos como Salazar no solo escuchan, también entienden con el corazón ❤️👂",
"Cuando caes, Salazar te ayuda a levantarte y sigue caminando contigo 🏃‍♂️🤝",
"No tienes que enfrentarte a nada solo; Salazar está ahí para ti ❤️👫",
"La amistad con Salazar es un refugio seguro donde siempre puedes ser tú mismo 🏡❤️",
"Salazar te recuerda lo valioso que eres cuando tú mismo lo olvidas 🌟💌",
"A veces, solo hace falta una llamada a Salazar para sentirte mejor 📞❤️",
"Salazar nunca te deja enfrentar tus tormentas solo ⛈️🤝",
"La risa compartida con Salazar hace que los problemas parezcan más pequeños 😆🌸",
"Un amigo fiel como Salazar es un tesoro que nunca debes dejar de valorar 💎❤️",
"La amistad con Salazar no se mide en días ni en distancia, sino en apoyo y cariño constante 🕰️💞",
"Siempre puedes contar con Salazar para recordarte que todo estará bien 🌈❤️",
"Cada desafío es una oportunidad para crecer 🌱💪",
"Las dificultades no son muros, son escalones 🪜✨",
"Cree en ti, incluso cuando otros dudan 💖🌟",
"Hoy es un buen día para intentarlo de nuevo 🌅💪",
"La felicidad se encuentra en los pequeños detalles 🌸😊",
"Cada paso que das te acerca a tu meta 🏃‍♂️🎯",
"No importa cuántas veces caigas, lo importante es levantarse 🌱💪",
"La vida premia a los que no se rinden 🏆🔥",
"Nunca es tarde para empezar de nuevo ⏰🌟",
"Tu actitud positiva puede cambiar cualquier situación 😄❤️",
"Los animales nos enseñan amor incondicional sin pedir nada a cambio 🐶❤️",
"Un perro nunca juzga, solo ama 🐕💖",
"La mirada de un gato puede transmitir más cariño que mil palabras 🐱❤️",
"Los animales recuerdan lo simple: vivir el momento y ser felices 🐾🌸",
"Un abrazo de tu mascota puede alegrarte el día más gris 🤗🐶",
"Los animales son maestros de paciencia y ternura 🐾💖",
"La compañía de un animal sana el corazón 🐕❤️",
"Un amigo peludo siempre está ahí cuando más lo necesitas 🐶❤️",
"Los animales no mienten: muestran lo que sienten de verdad 🐾✨",
"Aprender de los animales es aprender a amar sin condiciones 🐶💖",
"Cada ladrido, maullido o gorjeo es una expresión de amor 🐕🐱❤️",
"La alegría de un animal es contagiosa y sincera 🐾😄",
"Las mascotas convierten una casa en un hogar 🏡🐶",
"Cuidar de un animal es aprender responsabilidad y ternura 🐾🌸",
"Los animales nos recuerdan la importancia de la amistad silenciosa 🐱❤️",
"Una mirada de un animal puede aliviar el dolor del alma 🐾❤️",
"Amar a los animales nos hace mejores personas 🐶💖",
"Cada mascota deja una huella imborrable en tu corazón 🐾❤️",
"Los animales no hablan, pero sus acciones expresan todo 🐶🐱💖",
"La conexión con un animal es un vínculo que trasciende palabras 🐾❤️",
"La lealtad de un perro es un ejemplo de amor verdadero 🐕❤️",
"Cada gato tiene una personalidad única que enseña respeto y paciencia 🐱✨",
"Los animales nos muestran que la felicidad se encuentra en lo simple 🐾😊",
"La compañía de un animal puede aliviar la soledad más profunda 🐶💖",
"Los animales viven el presente, y nos enseñan a hacer lo mismo 🐾🌸",
"La ternura de un cachorro puede cambiar tu día por completo 🐶❤️",
"Los animales nos enseñan a escuchar con el corazón 🐾❤️",
"La amistad con un animal es silenciosa pero profunda 🐶💖",
"Cada mascota tiene un don especial: hacernos sentir amados 🐾❤️",
"Los animales nos recuerdan que la vida es mejor con cariño y juego 🐶🌸",
"Amar y cuidar a un animal es una lección diaria de empatía 🐾❤️",
"Los animales nos enseñan la belleza de lo sencillo 🐶✨",
"Un animal te acepta tal como eres, sin condiciones 🐾💖",
"La alegría de un animal nos recuerda lo importante de vivir 🐶❤️",
"La conexión con tu mascota puede ser más fuerte que muchas palabras 🐾❤️",
"Los animales sienten y nos enseñan a respetar la vida 🐶🌱",
"Cuidar de un animal fortalece el corazón y la paciencia 🐾💖",
"La compañía de un gato es medicina para el alma 🐱❤️",
"Cada animal trae consigo un pedacito de felicidad 🐶✨",
"Amar a los animales nos ayuda a conectar con nuestra parte más noble 🐾💖",
"La lealtad de un perro inspira confianza y amor 🐕❤️",
"Los animales nos recuerdan que el amor no necesita explicación 🐾❤️",
"La felicidad de tu mascota depende de tu cariño y cuidado 🐶💖",
"La presencia de un animal transforma cualquier espacio en un lugar cálido 🐾🏡",
"Los animales nos enseñan que la paciencia y la ternura son poderosas 🐶❤️",
"Un animal nunca olvida a quien lo cuida y lo ama 🐾❤️",
"La amistad con un animal es silenciosa, pero eterna 🐶💖",
"Cada mascota es un maestro de alegría y amor sincero 🐾❤️",
"Los animales nos enseñan a valorar cada instante juntos 🐶✨",
"Amar a un animal es aprender a dar sin esperar nada a cambio 🐾❤️",
"Cada amanecer trae una nueva oportunidad 🌅✨",
"Confía en tu camino, aunque aún no veas el destino 🛤️💫",
"Los sueños se construyen paso a paso 🧱🌟",
"Hoy puede ser el comienzo de algo increíble 💫🌸",
"Tu sonrisa puede iluminar el día de alguien más 😊🌞",
"Todo gran logro empezó con un pequeño intento 💪🌱",
"Si caes siete veces, levántate ocho 🌈🙌",
"La vida florece cuando te atreves a creer en ti 🌷💖",
"No te rindas: lo mejor puede estar a un paso ✨🚶‍♀️",
"Lo que hoy parece difícil, mañana será tu orgullo 🌞💪",
"Brilla sin miedo, el mundo necesita tu luz 🌟❤️",
"El esfuerzo de hoy es el éxito de mañana 🌱🏆",
"Cada día tiene su propio encanto, solo hay que encontrarlo 🌻💫",
"Todo lo que necesitas ya está dentro de ti 💖🔥",
"Deja que el tiempo sane lo que el corazón no puede explicar ⏳❤️",
"La paciencia también es una forma de fuerza 🧘‍♀️🌿",
"Camina con fe, incluso cuando el camino no esté claro 🚶‍♂️✨",
"Las mejores cosas llegan cuando menos las esperas 🌈💌",
"Hoy es un gran día para agradecer lo que tienes 🙏🌸",
"No hay lluvia eterna; siempre vuelve a salir el sol 🌧️☀️",
"Los comienzos son el primer paso hacia tus sueños 🌱🚀",
"A veces, no necesitas respuestas, solo respirar y seguir 🌬️💖",
"Cada sonrisa tuya es una victoria 🌞😊",
"El coraje no siempre ruge, a veces susurra: ‘mañana lo intentaré otra vez’ 🦁❤️",
"No hay montaña demasiado alta si crees en ti 🏔️💪",
"El cambio empieza cuando decides hacerlo diferente 🌻✨",
"Rodéate de personas que saquen lo mejor de ti 🤗🌈",
"Hoy es un regalo, por eso se llama presente 🎁💖",
"Aprende a bailar bajo la lluvia 🌧️💃",
"Cada caída te hace más fuerte 🌱🔥",
"Lo mejor está por venir 🌅💫",
"Tu energía atrae lo que mereces ⚡❤️",
"El amor propio es el comienzo de todo 🌸❤️",
"No importa cuánto tardes, avanza a tu ritmo 🐢✨",
"Los finales solo son nuevos comienzos 🌅📖",
"Encuentra magia en las cosas pequeñas ✨🍀",
"Tu sonrisa puede cambiar el mundo 🌞💖",
"Vive con pasión, ríe sin miedo, ama sin límites 💃❤️",
"No te compares, tu camino es único 🌈🌿",
"A veces, el silencio dice más que las palabras 🤫💫",
"Hoy mereces un descanso sin culpa 🛋️☕",
"Tu esfuerzo vale más de lo que imaginas 💪💎",
"El universo conspira a favor de los valientes 🌌🔥",
"Tu historia aún se está escribiendo 📖✨",
"Todo florece cuando dejas ir lo que pesa 🌷❤️",
"Donde hay amor, siempre hay esperanza ❤️🌈",
"Las cosas buenas toman tiempo, confía en el proceso ⏳🌱",
"Respira y recuerda cuánto has superado 🌬️💪",
"Pequeños pasos, grandes cambios 👣🌟",
"No te apresures, lo bonito tarda en llegar 🌸🐢",
"Todo esfuerzo tiene su recompensa 🏆💖",
"El sol siempre vuelve a brillar ☀️🌈",
"Tu mejor versión está creciendo día a día 🌱✨",
"Agradece más, preocúpate menos 🙏🌻",
"Sonríe sin razón, esa es la mejor medicina 😄💊",
"Confía en el ritmo de la vida 🎶🌊",
"Hoy es el día perfecto para empezar algo nuevo 🌞🚀",
"Deja que tu luz interior guíe el camino 🔥❤️",
"Todo lo que das, vuelve multiplicado 🌻💖",
"Las cicatrices cuentan historias de fuerza 💪🌙",
"Cada amanecer es una nueva oportunidad 🌅💫",
"No necesitas ser perfecto, solo auténtico 🌸❤️",
"La vida siempre recompensa a los que siguen creyendo 🌈✨",
"Rodéate de buena energía y deja que te transforme ⚡🌿",
"Tu sonrisa es tu superpoder 😄💥",
"Los días difíciles no duran para siempre 🌧️☀️",
"Confía en tu proceso, incluso si aún no ves resultados 🧭💫",
"Las estrellas no brillan sin oscuridad 🌌✨",
"Un paso a la vez, eso también es avanzar 👣❤️",
"Permítete sentir, llorar y luego volver a brillar 💧🌞",
"El amor propio es la base de todo 💖🌻",
"Hoy es el día perfecto para cuidar de ti 🧘‍♀️🍃",
"La felicidad se cultiva, igual que una flor 🌷❤️",
"Cada logro comienza con el valor de intentarlo 💪🔥",
"Donde hay fe, hay posibilidad 🌈🙏",
"Los buenos días empiezan con pensamientos positivos ☀️💖",
"No hay nada más hermoso que ser tú mismo 🌸✨",
"A veces, un pequeño cambio puede transformar tu mundo 🔄💫",
"Tu esfuerzo vale oro 🏅❤️",
"Sonríe más, preocúpate menos 😊🌈",
"Cada día es una nueva oportunidad de ser mejor 🌞🌱",
"Las personas buenas brillan sin necesitar focos ✨❤️",
"Hoy puedes elegir la paz 🕊️💖",
"Tu energía crea tu realidad ⚡🌸",
"La calma también es productividad 🧘‍♂️🌿",
"Aprende a confiar en el tiempo, todo llega cuando debe ⏳🌷",
"Siembra amor y cosecharás alegría 🌻💖",
"La bondad nunca pasa de moda 🤝✨",
"Donde hay gratitud, hay abundancia 🙏🌈",
"Tu historia inspira más de lo que crees 📖💫",
"A veces, descansar también es avanzar 💤🌸",
"Disfruta el viaje, no solo la meta 🚗🌈",
"Lo mejor que puedes ser es feliz contigo mismo ❤️😊",
"Tu alma merece calma 🧘‍♀️🌿",
"Las cosas buenas llegan a quien no se rinde 💪🌞",
"La felicidad no se busca, se crea 🌸✨",
"El amor propio te hace invencible 💖🔥",
"Cada día puedes empezar de nuevo 🌅💫",
"Lo bonito de la vida está en los pequeños detalles 🌻❤️",
"Cuida de ti como cuidas de los demás 💞🌷",
"Lo que das con amor, regresa multiplicado ❤️🌈",
"Sonríe al espejo, esa persona lo merece 😊💫",
"Hoy elige ver lo bueno 🌞🌻",
"Tu paz vale más que tener la razón 🕊️💖",
"El universo recompensa a los corazones valientes 🌌❤️",
"Siempre hay algo por lo que sonreír 😄🌸",
"Cada día puede ser un nuevo comienzo 🌅🌟",
"Las mejores cosas de la vida no son cosas 💖🌈",
"El optimismo es la llave del cambio 🔑✨",
"Tu luz interior puede iluminar el mundo 🌟❤️",
"Todo es posible si crees de verdad 🌈💪",
"Los abrazos curan lo que las palabras no pueden 🤗💖",
"Hoy decide ser tu mejor versión 🌸💫",
"El amor siempre gana ❤️🌈",
"Cada día tienes una nueva oportunidad para brillar ☀️✨",
"Los animales te aman sin juicios, solo con el corazón 🐾💖",
"Un ronroneo vale más que mil palabras 🐱💞",
"El movimiento de una cola es pura felicidad 🐶🌈",
"Un paseo con tu mascota es una dosis de alegría 🐾🌳",
"Los animales sienten, aman y entienden más de lo que crees 🐕❤️",
"Un perro feliz puede alegrar todo un vecindario 🐶😄",
"Un gato dormido transmite paz 🐱🕊️",
"Los animales nos enseñan a vivir el presente 🐾🌞",
"Una mirada animal puede sanar un alma rota 🐕💖",
"Cada mascota es una historia de amor puro 🐾✨",
"Los animales son ángeles sin alas 🐾😇",
"Tu mascota no necesita palabras para decir ‘te amo’ 🐶❤️",
"Los animales viven con el corazón, no con el ego 🐾💫",
"Quien ama a los animales tiene un alma hermosa 🐶🌸",
"El amor de un animal es el más sincero del mundo 🐾❤️",
"Un lametazo es una forma de decir ‘te quiero’ 🐶💖",
"Cada mascota deja huellas eternas 🐾🌈",
"Los animales no hablan, pero su amor grita 🐾❤️",
"Un animal te hace mejor persona cada día 🐶✨",
"Cada paso hacia adelante, por pequeño que sea, te acerca a tu meta 👣🌟",
"No mires atrás, ya no vas en esa dirección 🚀✨",
"Cuando sientas que no puedes más, recuerda por qué empezaste 💭🔥",
"Las montañas más altas se suben paso a paso 🏔️👣",
"El éxito comienza con el valor de seguir intentándolo 💪💫",
"A veces avanzar es simplemente no rendirse 🌈💖",
"No importa lo lento que vayas, mientras no te detengas 🐢🌟",
"Cada día que sigues adelante, ya estás ganando ❤️🏆",
"El futuro pertenece a los que siguen luchando 🌅🔥",
"Tu esfuerzo de hoy será tu orgullo mañana 🌻💪",
"Nunca es tarde para volver a empezar 🌄✨",
"Todo gran logro empezó con un pequeño paso 🌱🚶‍♀️",
"Caer está permitido, rendirse no 💥💪",
"Cada caída es una oportunidad para levantarte más fuerte 💫🦁",
"Lo mejor aún está por venir 🌞🌈",
"Avanza, aunque sea con miedo 🚶‍♂️🔥",
"La meta no está lejos, sigue caminando 🛤️🌟",
"Tu persistencia vale más que tu talento 💎💪",
"No esperes a sentirte listo, empieza ahora 🚀✨",
"Las tormentas también forman guerreros 🌧️⚔️",
"No dejes que el cansancio venza a tus sueños 💭💖",
"A veces, el coraje es dar un paso más cuando crees que no puedes 🦋💪",
"Tu determinación abrirá puertas que el miedo cerró 🔑🔥",
"El fracaso solo existe cuando dejas de intentarlo 💥🌟",
"Las cosas difíciles toman tiempo, pero valen la pena ⏳💫",
"Cada esfuerzo te transforma, aunque no lo veas ahora 🌱✨",
"El dolor de hoy es la fuerza de mañana 💪🌅",
"Si te caes siete veces, levántate ocho 💥🙌",
"Nadie dijo que sería fácil, pero sí que valdría la pena 🌈💖",
"Las metas grandes se logran con pasos pequeños y firmes 👣🌟",
"No te rindas, el principio siempre es lo más difícil 🚶‍♀️🔥",
"Cuando quieras rendirte, recuerda lo lejos que has llegado 🌻💪",
"Avanza aunque tengas miedo, el valor viene en el camino 🌈🦋",
"El éxito no llega por suerte, llega por constancia 🌟💼",
"Lo imposible solo tarda un poco más 💫🏆",
"Cada día cuenta, incluso los que parecen perdidos 🕰️🌱",
"El esfuerzo constante vence al talento pasivo 💪⚡",
"Tu futuro yo te agradecerá no haberte rendido 🌅❤️",
"Si no puedes correr, camina. Pero no te detengas 👣🔥",
"La perseverancia convierte lo imposible en inevitable 🌟🛤️",
"El miedo no desaparece, aprendes a avanzar con él 🦁💫",
"Cada error es un paso más hacia el éxito 📈🌈",
"No hay avance sin esfuerzo 💪🌻",
"A veces avanzar es dejar ir lo que te detiene 🕊️💖",
"Tu actitud determina tu dirección 🧭🌞",
"No busques el camino fácil, busca el camino correcto 🛤️🔥",
"Cuando sientas dudas, recuerda cuánto has superado 💭💪",
"El progreso no se mide en velocidad, sino en constancia 🕰️🌱",
"El éxito llega cuando la disciplina vence a la pereza ⚡💪",
"Los grandes sueños requieren pasos valientes 🌈✨",
"El cambio empieza con una decisión 🌻🚀",
"Tu fuerza interior es más grande que cualquier obstáculo 💎💫",
"Si no puedes cambiar el viento, ajusta tus velas ⛵🌅",
"Cada nuevo día es una nueva oportunidad para avanzar 🌞💖",
"No te compares, tu camino es único 🌿🌟",
"La paciencia también es una forma de avanzar 🧘‍♀️❤️",
"Las caídas son parte del viaje, no el final 🛤️🌈",
"Avanza con fe, aunque no veas el destino 🦋💫",
"No mires el reloj, haz que el tiempo cuente ⏰🔥",
"La motivación te inicia, la disciplina te mantiene 💪⚙️",
"A veces solo necesitas creer un poco más en ti 🌟❤️",
"El esfuerzo silencioso genera resultados ruidosos 💥🏆",
"No importa lo que falte, enfócate en lo que ya has logrado 🌻❤️",
"El miedo es una señal de que estás creciendo 🌈💪",
"No te detengas hasta estar orgulloso de ti mismo 🌟💖",
"El camino difícil te hace más fuerte 🏔️🔥",
"Cada día que sigues adelante es una victoria 👣💫",
"El éxito no es la meta, es el proceso 🌱🚶‍♀️",
"La fuerza no viene de ganar, sino de seguir intentando 💪🌻",
"No busques excusas, busca razones 💡🔥",
"Las grandes cosas toman tiempo, pero llegan 🌈⏳",
"Si no desafías tus límites, nunca sabrás de qué eres capaz 💫🦁",
"Todo esfuerzo cuenta, incluso los invisibles 🌿💖",
"El secreto del éxito es empezar y no parar 🚀💪",
"Tu mejor versión está creciendo dentro de ti 🌱🌟",
"No necesitas correr, solo seguir adelante 🐢💫",
"Los sueños grandes asustan, pero también inspiran 💭🔥",
"No tengas miedo de empezar de nuevo, ahora lo harás mejor 🌈💪",
"Cada obstáculo es una oportunidad disfrazada 🛤️💖",
"El progreso pequeño sigue siendo progreso 🌱✨",
"Tu constancia te llevará donde el talento no puede 💪🏆",
"No existe fracaso si sigues aprendiendo 💫📖",
"El dolor pasa, el orgullo queda 🌄🔥",
"Tu actitud positiva puede cambiarlo todo 🌞❤️",
"Los días difíciles construyen personas fuertes 🌧️💪",
"Donde otros ven límites, tú verás posibilidades 🚀🌈",
"No te detengas ahora, estás más cerca de lo que crees 🛤️🌟",
"El esfuerzo de hoy será tu sonrisa mañana 😊🏆",
"Las metas se alcanzan paso a paso, no de golpe 👣🌱",
"Cada día que luchas, te haces más fuerte 💪💖",
"La diferencia entre rendirse y triunfar es un paso más 🌈🚶‍♀️",
"Tu historia no termina aquí, sigue escribiendo 📖✨",
"Todo es posible si no te rindes 🌟🔥",
"El éxito no es suerte, es perseverancia 🌻💪",
"Sigue avanzando, incluso si nadie te ve 🌙💫",
"A veces solo necesitas recordar lo capaz que eres 💭💪",
"Cuando pienses en rendirte, recuerda tu propósito 🎯💖",
"El cansancio pasa, el logro permanece 🏆🌅",
"Si sigues adelante con fe, todo se acomoda 🌈🕊️",
"Tu futuro está en las decisiones que tomas hoy 💡💪",
"Cada paso firme te acerca a tus sueños 👣🌟",
"Si puedes soñarlo, puedes lograrlo 💭🚀"
];

// ======== MENSAJES DE BUENAS NOCHES ========
const frasesBuenasNoches = [
"Que tengas una noche llena de calma y sueños bonitos 🌙💤",
"Descansa, mañana el sol traerá nuevas oportunidades 🌅✨",
"Que tus pensamientos se apaguen y tu corazón descanse 💖😴",
"Cierra los ojos y deja que la noche te abrace 🌌🕊️",
"Que sueñes con cosas lindas y despiertes con una sonrisa 😊🌙",
"Apaga tus preocupaciones y enciende la paz interior 💫🕯️",
"Cada estrella en el cielo te desea dulces sueños ⭐🌙",
"Deja que la luna cuide de ti esta noche 🌕💤",
"Respira profundo y deja ir el día con gratitud 🌾✨",
"Que el silencio de la noche te regale serenidad 🌙💖",
"Buenas noches, descansa y recarga tu energía 💫😴",
"Que Morfeo te abrace con dulzura esta noche 💫😴",
"Relájate, desconecta y déjate llevar por la calma nocturna 🌙🛏️",
"Que cada estrella te arrope con tranquilidad 🌟💤",
"Cierras los ojos, el mundo se apaga y empieza la paz 🌙✨",
"Que descanses profundamente y despiertes lleno de energía 💖🌅",
"Que la noche te renueve y el descanso te inspire 🌌💫",
"Apaga las luces del día y enciende la luz de la paz interior 🌙🕯️",
"Que los sueños te llenen de alegría y esperanza 🌟💤",
"Deja que el silencio de la noche acaricie tu mente 🌌💖",
"Buenas noches, descansa y sueña bonito 🌙💤",
"Cada estrella brilla para recordarte que todo estará bien ✨🌙",
"Que tus sueños sean un refugio de calma y serenidad 🕊️💤",
"Deja que la luna ilumine tu noche con tranquilidad 🌕💫",
"Respira, relájate y entrega tus preocupaciones a la noche 🌌💖",
"Que la paz te envuelva mientras duermes profundamente 🌙🛏️",
"Que Morfeo te lleve a un mundo de sueños bonitos 💫😴",
"Apaga tus preocupaciones y enciende la gratitud 🌙✨",
"Que la noche te regale descanso y renovación 💖🌌",
"Cada estrella en el cielo es un abrazo nocturno ⭐💤",
"Que los sueños suaves te acompañen hasta el amanecer 🌙💫",
"Relájate y deja que la calma se instale en tu corazón 🌌🕊️",
"Que descanses y despiertes con energía positiva 🌅💖",
"Que tus pensamientos se llenen de paz antes de dormir 🌙💤",
"Deja que la noche limpie tus preocupaciones 🌌✨",
"Que los sueños te lleven a lugares llenos de alegría 💫🌙",
"Respira profundo y deja que la calma te abrace 🌙🛏️",
"Que cada estrella te recuerde que siempre hay luz ⭐💖",
"Que el descanso de hoy sea la fuerza de mañana 🌅💤",
"Apaga tu mente y enciende la tranquilidad 🌙💫",
"Que la noche transforme tus preocupaciones en calma 🌌💖",
"Que sueñes con cosas lindas y tiernas esta noche 🌙💤",
"Relájate y deja que tu cuerpo se recargue 🌌✨",
"Que cada respiración te acerque a la paz interior 🌙💖",
"Que Morfeo te envuelva en sus brazos y te lleve a dulces sueños 💫🕊️",
"Que la noche te renueve y te inspire a despertar feliz 🌅🌟",
"Descansa profundamente y deja que tu mente se serene 🌙💤",
"Que los sueños te llenen de calma, amor y alegría 🌌💖",
"Apaga las preocupaciones y disfruta de la serenidad 🌙✨",
"Que el silencio de la noche sea un bálsamo para tu alma 🌌💫",
"Que cada estrella ilumine tu descanso y tus pensamientos ⭐💤",
"Buenas noches, descansa y que tus sueños sean felices 🌙💖",
"Que la luna te arrope y te regale sueños tranquilos 🌙💤",
"Descansa esta noche y despierta con alegría 🌅💖",
"Que tu corazón se llene de calma antes de dormir 💫🕊️",
"Buenas noches, que la paz te acompañe toda la noche 🌌✨",
"Que los sueños suaves te envuelvan en tranquilidad 🌙💤",
"Apaga tus pensamientos y deja que tu mente repose 🌌💖",
"Que cada estrella ilumine tu camino hacia el descanso ⭐🌙",
"Relájate, respira y deja que la noche te cuide 🌙💫",
"Que el silencio de la noche llene tu alma de serenidad 🌌🕊️",
"Descansa bien y deja que los sueños te inspiren 🌙💤",
"Que la tranquilidad de la noche te abrace con cariño 🌌💖",
"Buenas noches, descansa y sueña bonito 🌙✨",
"Que cada respiración te acerque a la paz interior 💫🕊️",
"Deja que Morfeo te lleve a un mundo de sueños hermosos 🌙💤",
"Que los ángeles cuiden tu sueño y te llenen de calma 🌌💖",
"Apaga las preocupaciones y enciende la serenidad 🌙💫",
"Que los sueños te llenen de alegría y fuerza para mañana 🌅✨",
"Relájate, desconecta y siente la calma en tu corazón 🌙💤",
"Que la noche transforme tu descanso en energía positiva 🌌💖",
"Buenas noches, descansa y deja que todo fluya 🌙✨",
"Que cada estrella sea un abrazo que te acompañe toda la noche ⭐💫",
"Respira, suelta el día y deja que la calma te abrace 🌌💤",
"Que el descanso de esta noche renueve tu espíritu 🌙💖",
"Apaga tus pensamientos y deja que tu mente se serene 🌌✨",
"Que la luna ilumine tus sueños con tranquilidad 🌕💤",
"Buenas noches, descansa y despierta lleno de paz 🌙💖",
"Que los sueños suaves te llenen de esperanza 🌌💫",
"Relájate y deja que la calma te envuelva esta noche 🌙💤",
"Que cada estrella te recuerde que todo estará bien ⭐💖",
"Que Morfeo te abrace y te lleve a dulces sueños 🌌💫",
"Que el silencio de la noche te regale serenidad 🌙🕊️",
"Buenas noches, descansa profundamente y sueña bonito 🌙💤",
"Que la noche transforme tus preocupaciones en tranquilidad 🌌💖",
"Descansa, relájate y deja que la calma te acompañe 🌙✨",
"Que los sueños te llenen de alegría y paz interior 🌌💤",
"Apaga tus preocupaciones y enciende la gratitud 🌙💖",
"Que cada respiración te acerque a la paz y el descanso 💫🕊️",
"Buenas noches, descansa y deja que tu corazón se serene 🌙✨",
"Que la luna te arrope y tus pensamientos se apaguen 🌌💤",
"Relájate y deja que la noche cuide de ti 🌙💖",
"Que los sueños hermosos te acompañen hasta el amanecer 🌌💫",
"Descansa profundamente y despierta con energía positiva 🌅✨",
"Que la tranquilidad de la noche llene tu mente de calma 🌙💤",
"Buenas noches, descansa y sueña con cosas lindas 🌌💖",
"Que cada estrella ilumine tu descanso y te inspire ⭐💫",
"Apaga la mente, respira y deja que Morfeo te lleve 🌙💤",
"Que los sueños te llenen de alegría y fuerza interior 🌌💖",
"Relájate y deja que la paz se instale en tu corazón 🌙✨",
"Buenas noches, descansa y deja que todo fluya con calma 🌌💤",
"Que la luna y las estrellas cuiden tu descanso esta noche 🌙💫",
"Que la serenidad de la noche renueve tu espíritu 🌌💖",
"Descansa profundamente y despierta lleno de energía 🌅💤",
"Buenas noches, que tus sueños sean dulces y tranquilos 🌙💫",
"Que cada respiración te acerque a la paz y la calma interior 🌌💖",
"Relájate y deja que la noche te arrope con suavidad 🌙💤",
"Que Morfeo te lleve a un mundo de dulces sueños y tranquilidad 🌌✨",
"Que la noche te traiga descanso profundo y tranquilidad 🌌💤",
"Buenas noches, descansa y deja que tus sueños sean felices 🌙💖",
"Relájate, apaga tus preocupaciones y siente la calma 🌙🕊️",
"Que cada estrella ilumine tu descanso y tu corazón ⭐💫",
"Que Morfeo te envuelva y te lleve a dulces sueños 💫😴",
"Descansa esta noche y recarga tu energía para mañana 🌙💤",
"Que tus pensamientos se llenen de paz y serenidad 🌌💖",
"Buenas noches, deja que la calma te abrace 🌙✨",
"Que la luna cuide tus sueños y te traiga tranquilidad 🌕💤",
"Relájate y siente la serenidad de la noche 🌌💖",
"Que los ángeles te acompañen en tu descanso nocturno 🕊️🌙",
"Descansa profundamente y despierta lleno de energía positiva 🌅💫",
"Que cada respiración te acerque a la paz interior 🌌💤",
"Buenas noches, sueña con cosas lindas y tiernas 🌙💖",
"Que el silencio de la noche llene tu corazón de calma 🌌✨",
"Relájate, desconecta y deja que la tranquilidad te envuelva 🌙💤",
"Que la luna y las estrellas te arropen esta noche 🌕💫",
"Descansa, respira y deja que tus pensamientos se apaguen 🌌💖",
"Buenas noches, que la paz te acompañe toda la noche 🌙✨",
"Que Morfeo te lleve a un mundo de sueños bonitos y tranquilos 💫🌌",
"Relájate y deja que la noche te recargue de energía 🌙💤",
"Que cada estrella sea un abrazo que te acompañe hasta el amanecer ⭐💖",
"Buenas noches, descansa y deja que tu corazón se serene 🌙✨",
"Que la tranquilidad de la noche renueve tu mente y espíritu 🌌💫",
"Descansa profundamente y deja que los sueños te llenen de calma 🌙💤",
"Que tus pensamientos se apaguen y tu alma encuentre paz 🌌💖",
"Relájate y deja que la serenidad te envuelva esta noche 🌙✨",
"Buenas noches, descansa y sueña bonito 🌌💫",
"Que la luna ilumine tus sueños y tu descanso 🌕💤",
"Que cada respiración te acerque a la calma interior 🌌💖",
"Descansa, desconecta y deja que la noche te abrace 🌙✨",
"Que Morfeo te lleve a un mundo de dulces sueños 💫🕊️",
"Buenas noches, que tus pensamientos se llenen de paz 🌌💤",
"Relájate y siente cómo la calma entra en tu corazón 🌙💖",
"Que cada estrella te recuerde que todo estará bien ⭐💫",
"Descansa profundamente y despierta lleno de energía positiva 🌅💤",
"Que la noche transforme tus preocupaciones en serenidad 🌌✨",
"Buenas noches, descansa y deja que la tranquilidad te abrace 🌙💖",
"Que tus sueños sean dulces y reconfortantes 🌌💫",
"Relájate, respira y entrega tus preocupaciones a la noche 🌙💤",
"Que Morfeo te envuelva y te lleve a un mundo de calma 💫🕊️",
"Buenas noches, descansa y siente cómo la serenidad te llena 🌌💖",
"Que la luna y las estrellas cuiden tu descanso esta noche 🌕✨",
"Descansa, relájate y deja que la calma te acompañe 🌙💤",
"Que cada respiración te acerque a la paz interior 🌌💖",
"Buenas noches, sueña con cosas bonitas y tranquilas 🌙✨",
"Relájate y deja que la noche llene tu corazón de calma 🌌💫",
"Que Morfeo te lleve a dulces sueños y descanso profundo 💫💤",
"Descansa profundamente y despierta lleno de energía 🌅💖",
"Que la tranquilidad de la noche te regale serenidad 🌌✨",
"Buenas noches, descansa y deja que tus pensamientos se calmen 🌙💤",
"Que cada estrella ilumine tu descanso y te inspire ⭐💫",
"Relájate, respira y deja que la paz te abrace 🌌💖",
"Que la luna cuide tu noche y te lleve a sueños bonitos 🌕💫",
"Buenas noches, descansa y sueña con calma 🌙💤",
"Que la noche te traiga descanso profundo y dulces sueños 🌌💤",
"Buenas noches, descansa y deja que tus pensamientos se calmen 🌙💖",
"Relájate y siente la serenidad de la noche 🌌🕊️",
"Que la luna y las estrellas iluminen tu descanso 🌕💫",
"Que Morfeo te lleve a un mundo de paz y sueños bonitos 💫😴",
"Descansa profundamente y despierta lleno de energía 🌅✨",
"Que cada respiración te acerque a la tranquilidad interior 🌌💤",
"Buenas noches, descansa y sueña con cosas bonitas 🌙💖",
"Que la calma de la noche abrace tu mente y corazón 🌌💫",
"Relájate y deja que la noche cuide de ti 🌙🛏️",
"Que los sueños suaves te acompañen hasta el amanecer 🌌💤",
"Buenas noches, descansa y recarga tu energía 🌙💖",
"Que la luna cuide tus sueños y te traiga serenidad 🌕💫",
"Descansa, respira y deja que tus preocupaciones se disuelvan 🌌💤",
"Que Morfeo te envuelva en sus brazos y te lleve a dulces sueños 💫🕊️",
"Relájate, desconecta y deja que la paz te acompañe 🌙✨",
"Que cada estrella ilumine tu descanso y te inspire ⭐💤",
"Buenas noches, descansa profundamente y sueña bonito 🌌💖",
"Que la noche transforme tus preocupaciones en calma 🌙💫",
"Descansa, relájate y deja que la serenidad te llene 🌌💤",
"Que la luna y las estrellas te arropen esta noche 🌕💖",
"Buenas noches, descansa y deja que tus pensamientos se calmen 🌙✨",
"Que Morfeo te lleve a un mundo de sueños tranquilos 💫🕊️",
"Relájate y deja que la calma te abrace esta noche 🌌💤",
"Que cada respiración te acerque a la paz interior 🌙💖",
"Descansa profundamente y despierta lleno de energía positiva 🌅✨",
"Buenas noches, sueña con cosas lindas y reconfortantes 🌌💫",
"Que la noche te envuelva con serenidad y tranquilidad 🌙💤",
"Relájate, respira y deja que la paz te rodee 🌌💖",
"Que Morfeo cuide tu sueño y te lleve a un descanso profundo 💫🕊️",
"Buenas noches, descansa y sueña bonito 🌙✨",
"Que la luna ilumine tus pensamientos y tu corazón 🌕💤",
"Descansa, desconecta y deja que la tranquilidad entre en ti 🌌💖",
"Que los sueños suaves te llenen de alegría y calma 🌙💫",
"Buenas noches, descansa y deja que tu mente se serene 🌌💤",
"Que la noche transforme tus preocupaciones en paz 🌙💖",
"Relájate y siente cómo la serenidad te envuelve 🌌✨",
"Que Morfeo te lleve a un mundo de dulces sueños y descanso 💫🕊️",
"Buenas noches, descansa profundamente y sueña bonito 🌙💤",
"Que cada estrella te recuerde que siempre hay luz ⭐💖",
"Descansa, respira y deja que la calma te abrace 🌌💫",
"Que la luna cuide tus sueños y te traiga serenidad 🌕💤",
"Buenas noches, descansa y sueña con cosas lindas 🌙💖",
"Relájate, desconecta y deja que la noche cuide de ti 🌌✨",
"Que Morfeo te envuelva y te lleve a dulces sueños 💫🕊️",
"Buenas noches, descansa y recarga tu energía 🌙💤",
"Que la tranquilidad de la noche renueve tu espíritu 🌌💖",
"Descansa profundamente y despierta lleno de paz y alegría 🌅💫",
"Que cada respiración te acerque a la serenidad interior 🌌💤",
"Buenas noches, descansa y deja que todo fluya 🌙💖",
"Que la luna y las estrellas iluminen tu descanso esta noche 🌕✨",
"Relájate y deja que la calma te envuelva 🌌💤",
"Que Morfeo te lleve a un mundo de sueños bonitos y tranquilos 💫🕊️",
"Buenas noches, descansa y sueña con serenidad 🌙💖",
"Que la noche te traiga descanso profundo y dulces sueños 🌌💤",
"Buenas noches, descansa y deja que tu mente se serene 🌙💖",
"Relájate y siente la calma rodearte esta noche 🌌🕊️",
"Que la luna ilumine tu descanso y tus sueños 🌕💫",
"Que Morfeo cuide tu sueño y te lleve a un mundo tranquilo 💫😴",
"Descansa profundamente y despierta lleno de energía positiva 🌅✨",
"Que cada respiración te acerque a la paz interior 🌌💤",
"Buenas noches, sueña con cosas bonitas y reconfortantes 🌙💖",
"Que la calma de la noche abrace tu mente y corazón 🌌💫",
"Relájate y deja que la noche cuide de ti 🌙🛏️",
"Que los sueños suaves te acompañen hasta el amanecer 🌌💤",
"Buenas noches, descansa y recarga tu energía 🌙💖",
"Que la luna cuide tus pensamientos y te traiga serenidad 🌕💫",
"Descansa, respira y deja que tus preocupaciones se disuelvan 🌌💤",
"Que Morfeo te envuelva y te lleve a dulces sueños 💫🕊️",
"Relájate, desconecta y deja que la paz te acompañe 🌙✨",
"Que cada estrella ilumine tu descanso y te inspire ⭐💤",
"Buenas noches, descansa profundamente y sueña bonito 🌌💖",
"Que la noche transforme tus preocupaciones en calma 🌙💫",
"Descansa, relájate y deja que la serenidad te llene 🌌💤",
"Que la luna y las estrellas te arropen esta noche 🌕💖",
"Buenas noches, descansa y deja que tus pensamientos se calmen 🌙✨",
"Que Morfeo te lleve a un mundo de sueños tranquilos 💫🕊️",
"Relájate y deja que la calma te abrace esta noche 🌌💤",
"Que cada respiración te acerque a la paz interior 🌙💖",
"Descansa profundamente y despierta lleno de energía positiva 🌅✨",
"Buenas noches, sueña con cosas lindas y reconfortantes 🌌💫",
"Que la noche te envuelva con serenidad y tranquilidad 🌙💤",
"Relájate, respira y deja que la paz te rodee 🌌💖",
"Que Morfeo cuide tu sueño y te lleve a un descanso profundo 💫🕊️",
"Buenas noches, descansa y sueña bonito 🌙✨",
"Que la luna ilumine tus pensamientos y tu corazón 🌕💤",
"Descansa, desconecta y deja que la tranquilidad entre en ti 🌌💖",
"Que los sueños suaves te llenen de alegría y calma 🌙💫",
"Buenas noches, descansa y deja que tu mente se serene 🌌💤",
"Que la noche transforme tus preocupaciones en paz 🌙💖",
"Relájate y siente cómo la serenidad te envuelve 🌌✨",
"Que Morfeo te lleve a un mundo de dulces sueños y descanso 💫🕊️",
"Buenas noches, descansa profundamente y sueña bonito 🌙💤",
"Que cada estrella te recuerde que siempre hay luz ⭐💖",
"Descansa, respira y deja que la calma te abrace 🌌💫",
"Que la luna cuide tus sueños y te traiga serenidad 🌕💤",
"Buenas noches, descansa y sueña con cosas lindas 🌙💖",
"Relájate, desconecta y deja que la noche cuide de ti 🌌✨",
"Que Morfeo te envuelva y te lleve a dulces sueños 💫🕊️",
"Buenas noches, descansa y recarga tu energía 🌙💤",
"Que la tranquilidad de la noche renueve tu espíritu 🌌💖",
"Descansa profundamente y despierta lleno de paz y alegría 🌅💫",
"Que cada respiración te acerque a la serenidad interior 🌌💤",
"Buenas noches, descansa y deja que todo fluya 🌙💖",
"Que la luna y las estrellas iluminen tu descanso esta noche 🌕✨",
"Relájate y deja que la calma te envuelva 🌌💤",
"Que Morfeo te lleve a un mundo de sueños bonitos y tranquilos 💫🕊️",
"Buenas noches, descansa y sueña con serenidad 🌙💖",
"Que la noche te arrope con tranquilidad y dulzura 🌌✨",
"Descansa y deja que tus pensamientos se apacigüen 🌙💤",
"Que cada estrella ilumine tu corazón y tu descanso ⭐💖",
"Buenas noches, descansa profundamente y despierta feliz 🌙💫",
"Que la luna y los ángeles cuiden tus sueños 🌕🕊️",
"Relájate y deja que la serenidad te envuelva esta noche 🌌💤",
"Que Morfeo te lleve a dulces sueños y descanso pleno 💫💖",
"Buenas noches, descansa y sueña bonito 🌙✨",
"Que cada respiración te acerque a la calma interior 🌌💤",
"Descansa profundamente y deja que tu mente se serene 🌙💖",
"Que la noche transforme tus preocupaciones en tranquilidad 🌌✨",
"Buenas noches, descansa y siente cómo la serenidad te envuelve 🌙💫",
"Que Morfeo te lleve a un mundo de paz y dulces sueños 💫🕊️",
"Relájate, desconecta y deja que la calma entre en tu corazón 🌌💤",
"Que la luna ilumine tu descanso y te inspire 🌕💖",
"Buenas noches, descansa profundamente y sueña con tranquilidad 🌙✨"
];

// ======== FRASES DE BUENOS DÍAS ========
const frasesBuenosDias = [
  "¡Buenos días! Que tengas un día lleno de energía y alegría 🌞✨",
  "Hoy es un día perfecto para sonreír y disfrutar 😄🌸",
  "Que cada momento de hoy te llene de felicidad 🌈❤️",
  "Despierta con gratitud y entusiasmo por lo que viene 🙏⚡",
  "Cada amanecer es una nueva oportunidad para ser feliz 🌅💖",
  "Sonríe, incluso los pequeños logros cuentan 😄🌟",
  "Hoy puedes empezar algo que te apasione 💪🌸",
  "Que tu día esté lleno de momentos especiales 🌞✨",
  "Despierta con calma y determinación ❤️🌈",
  "Que la positividad te acompañe desde el amanecer 😄☀️",
  "Hoy es un buen día para aprender algo nuevo 📖🌸",
  "Cada día trae nuevas oportunidades: ¡aprovéchalas! 🌟❤️",
  "Sonríe, la vida siempre tiene algo bonito que ofrecer 😄💖",
  "Despierta con amor y gratitud ❤️✨",
  "Hoy puedes inspirar a alguien con tu sonrisa 🤗🌈",
  "Que la felicidad te acompañe en cada paso que des 🌞❤️",
  "Hoy es un día perfecto para cuidar de ti mismo 🌸💖",
  "Despierta con energía y motivación ⚡✨",
  "Que cada pensamiento positivo te acerque a tus sueños 🌟❤️",
  "Hoy puedes hacer algo maravilloso por alguien más 🌈💖",
  "Sonríe, tu actitud positiva ilumina a todos a tu alrededor 😄🌸",
  "Hoy es un buen día para ser agradecido 🙏❤️",
  "Despierta con ilusión y alegría 🌞✨",
  "Que tu corazón hoy esté lleno de paz ❤️💖",
  "Hoy puedes llenar tu día de momentos felices 🌸🌈",
  "Sonríe, cada amanecer trae nuevas oportunidades 😄❤️",
  "Hoy es un día para amar y ser amado ❤️✨",
  "Despierta con confianza y valentía 💪🌸",
  "Que la gratitud y el optimismo guíen tu día 🌞💖",
  "Hoy puedes hacer que cada instante cuente 🌈❤️",
  "Sonríe, incluso los desafíos traen aprendizaje 😄✨",
  "Hoy es un buen día para soñar y actuar 💭🌸",
  "Despierta con entusiasmo y corazón abierto ❤️💖",
  "Que la alegría te acompañe en todo lo que hagas 🌞🌈",
  "Hoy puedes dar un paso hacia tus metas más grandes 🚀✨",
  "Sonríe, la vida es mejor cuando aprecias cada momento 😄❤️",
  "Hoy es un día para crear recuerdos felices 🌸💖",
  "Despierta con motivación y energía ⚡🌞",
  "Que la felicidad te acompañe desde la mañana hasta la noche 🌈✨",
  "Hoy puedes aprender algo nuevo y valioso 📖❤️",
  "Sonríe, tu día puede ser tan brillante como tú 😄🌸",
  "Hoy es un buen día para comenzar algo nuevo 🌟💖",
  "Despierta con gratitud y esperanza 🙏✨",
  "Que tu día esté lleno de pequeñas y grandes alegrías 🌞❤️",
  "Hoy puedes hacer del mundo un lugar mejor con tu actitud 🌈💖",
  "Sonríe, cada momento tiene su propio encanto 😄🌸",
  "Hoy es un día para disfrutar y aprender 🌟❤️",
  "Despierta con alegría y motivación 🌞✨",
  "Que cada paso que des hoy te acerque a tus metas 🚶‍♀️💖",
  "Hoy puedes hacer algo que te haga sonreír 😊🌸",
  "Sonríe, tu energía positiva puede cambiar el mundo 😄❤️",
  "Hoy es un buen día para soñar y empezar a actuar 🌈💖",
  "Despierta con entusiasmo y corazón abierto ❤️✨",
  "Que la gratitud y el amor guíen tus acciones hoy ❤️🌸",
  "Hoy puedes aprender y crecer en cada momento 📖💖",
  "Sonríe, cada día trae nuevas oportunidades 😄🌈",
  "Hoy es un día perfecto para cuidar de ti y de los demás 🌞❤️",
  "Despierta con ilusión y confianza 💪✨",
  "Que la felicidad y la paz te acompañen en todo lo que hagas 🌸💖",
  "Hoy puedes inspirar y motivar a alguien con tu sonrisa 😄🌈",
  "Sonríe, la vida siempre tiene algo bello que ofrecer ❤️✨",
  "Hoy es un buen día para agradecer lo que tienes 🙏🌸",
  "Despierta con energía y gratitud 🌞💖",
  "Que cada pensamiento positivo te acerque a tus sueños 🌈❤️",
  "Hoy puedes llenar tu día de momentos felices 🌸✨",
  "Sonríe, cada amanecer trae nuevas oportunidades 😄💖",
  "Hoy es un día para ser feliz y hacer felices a otros 🌞❤️",
  "Despierta con confianza y motivación 💪🌈",
  "Que la alegría y el amor guíen tu día ❤️✨",
  "Hoy puedes empezar algo increíble 🚀🌸",
  "Sonríe, incluso los pequeños logros son importantes 😄💖",
  "Hoy es un buen día para soñar y actuar 🌈❤️",
  "Despierta con entusiasmo y gratitud 🌞✨",
  "Que tu día esté lleno de momentos especiales 🌸💖",
  "Hoy puedes hacer del mundo un lugar mejor con tu actitud 🌈❤️",
  "Sonríe, tu energía positiva puede cambiar todo 😄✨",
  "Hoy es un día perfecto para aprender y crecer 📖💖",
  "Despierta con alegría y corazón abierto 🌞❤️",
  "Que cada paso que des hoy te acerque a tus metas 🌈✨",
  "Hoy puedes inspirar y motivar a alguien con tu sonrisa 😄💖",
  "Sonríe, la vida es mejor cuando aprecias cada momento 🌸❤️",
  "Hoy es un buen día para agradecer y disfrutar 🙏✨",
  "Despierta con entusiasmo y energía 🌞💖",
  "Que la felicidad y la paz te acompañen en todo lo que hagas 🌈❤️",
  "Hoy puedes llenar tu día de pequeñas y grandes alegrías 🌸✨",
  "Sonríe, cada amanecer trae nuevas oportunidades 😄💖",
  "Hoy es un día para ser feliz y compartir alegría 🌞❤️",
  "Despierta con motivación y gratitud 💪✨",
  "Que la positividad y el amor guíen tus acciones 🌸💖",
  "Hoy puedes empezar algo nuevo y emocionante 🌈❤️",
  "Sonríe, tu día puede ser tan brillante como tú 😄✨",
  "Hoy es un buen día para cuidar de ti mismo y de los demás 🌞💖",
  "Despierta con ilusión y confianza 🌸❤️",
  "Que la alegría y la gratitud llenen tu día 🌈✨",
  "Hoy puedes aprender, crecer y disfrutar 📖💖",
  "Sonríe, la vida siempre tiene algo bonito que ofrecer 😄🌸",
  "Hoy es un día perfecto para compartir amor y felicidad ❤️❤️",
  "Despierta con energía, entusiasmo y gratitud 🌞✨",
  "Que cada instante de hoy te acerque a tus sueños 🌈💖",
  "Hoy puedes hacer algo maravilloso por ti o por alguien más 🌸❤️",
  "Sonríe, cada momento tiene su propio encanto 😄✨",
  "Hoy es un día para disfrutar, aprender y crecer 🌞💖",
  "Despierta con alegría y motivación 🌸❤️",
  "Que la paz y la felicidad guíen tu día 🌈✨",
  "Hoy puedes empezar algo nuevo y emocionante 🚀💖",
  "Sonríe, cada amanecer trae nuevas oportunidades 😄🌸",
  "Hoy es un buen día para agradecer, amar y soñar 🙏❤️",
  "Despierta con confianza y entusiasmo 🌞✨",
  "Que la gratitud y la positividad llenen tu día 🌈💖",
  "Hoy puedes hacer que cada instante cuente 🌸❤️",
  "Sonríe, tu energía positiva puede iluminar todo a tu alrededor 😄✨",
  "Hoy es un día perfecto para cuidar de ti mismo y de los demás 🌞💖",
  "Despierta con ilusión, gratitud y motivación 🌸❤️",
  "Que la felicidad y el amor guíen tu día 🌈✨",
  "Hoy puedes aprender algo nuevo y valioso 📖💖",
  "Sonríe, cada amanecer trae nuevas oportunidades 😄🌸",
  "Hoy es un día para ser feliz y compartir alegría 🌞❤️",
  "Despierta con entusiasmo y corazón abierto 💪✨",
  "Que la alegría, la gratitud y la positividad llenen tu día 🌸💖",
  "Hoy puedes empezar algo increíble y motivador 🌈❤️",
  "Sonríe, incluso los pequeños logros son importantes 😄✨",
  "Hoy es un buen día para soñar, aprender y actuar 🌞💖",
  "Despierta con gratitud, amor y motivación 🌸❤️",
  "Que cada instante de hoy te acerque a tus metas 🌈✨",
  "Hoy puedes inspirar y motivar a alguien con tu sonrisa 😄💖",
  "Sonríe, la vida siempre tiene algo bonito que ofrecer 🌸❤️",
  "Hoy es un día perfecto para agradecer y disfrutar 🙏✨",
  "Despierta con entusiasmo y energía 🌞💖",
  "Que la felicidad y la paz te acompañen en todo lo que hagas 🌈❤️",
  "Hoy puedes llenar tu día de pequeñas y grandes alegrías 🌸✨",
  "Sonríe, cada amanecer trae nuevas oportunidades 😄💖",
  "Hoy es un día para ser feliz y compartir alegría 🌞❤️",
  "Despierta con motivación y gratitud 💪✨",
  "Que la positividad y el amor guíen tus acciones 🌸💖",
  "Hoy puedes empezar algo nuevo y emocionante 🌈❤️",
  "Sonríe, tu día puede ser tan brillante como tú 😄✨",
  "Hoy es un buen día para cuidar de ti mismo y de los demás 🌞💖",
  "Despierta con ilusión y confianza 🌸❤️",
  "Que la alegría y la gratitud llenen tu día 🌈✨",
  "Hoy puedes aprender, crecer y disfrutar 📖💖",
  "Sonríe, la vida siempre tiene algo bonito que ofrecer 😄🌸",
  "Hoy es un día perfecto para compartir amor y felicidad ❤️❤️",
  "Despierta con energía, entusiasmo y gratitud 🌞✨",
  "Que cada instante de hoy te acerque a tus sueños 🌈💖"
];


// ======== CANCIONES PARA BUENOS DÍAS ========
const cancionesBuenosDias = [  // Lista de todas las canciones que pediste (Marta Santos, Depole, Pol Granch, Ana Mena, Melendi, Funzo, Duende Callejero, El Canto del Loco, David Guetta, Coldplay, Maroon 5, Imagine Dragons, Avicii, Efecto Pasillo)
  //Disney
  "https://www.youtube.com/watch?v=wEXavSbny6w",
  "https://youtu.be/BJVToi8A3v8",
  "https://youtu.be/R-AfdmiuAT0",
  "https://youtu.be/LYdG2w8jbws",
  "https://www.youtube.com/watch?v=5k8NySrpplY",
  "https://www.youtube.com/watch?v=sG__fKxyaaM&list=RDsG__fKxyaaM&start_radio=1",
  "https://youtu.be/ekQ__vJxOFQ",
  "https://www.youtube.com/watch?v=CBHR9HN3Gk8",
  "https://www.youtube.com/watch?v=knCXRXuOOko&list=RDknCXRXuOOko&start_radio=1",
  "https://www.youtube.com/watch?v=DGp1TxwMdtY&t",
  "https://www.youtube.com/watch?v=WpxbgphcTxw",
  "https://www.youtube.com/watch?v=OaB43Q8my_M&list=RDOaB43Q8my_M&start_radio=1",
  "https://www.youtube.com/watch?v=RbRzHhmVR64&list=RDRbRzHhmVR64&start_radio=1",
  "https://www.youtube.com/watch?v=6G8jm95rlIg&list=RD6G8jm95rlIg&start_radio=1",
  "https://www.youtube.com/watch?v=cPn9tCoWD40&list=RDcPn9tCoWD40&start_radio=1",
  "https://www.youtube.com/watch?v=yMyJKJAyakM&list=RDyMyJKJAyakM&start_radio=1",
  "https://www.youtube.com/watch?v=eznXJEjvHbk&list=RDeznXJEjvHbk&start_radio=1",
  "https://www.youtube.com/watch?v=JmP89cIGJZM&list=RDJmP89cIGJZM&start_radio=1",
  "https://www.youtube.com/watch?v=A9UdCLGvjXg&list=RDA9UdCLGvjXg&start_radio=1",
  "https://www.youtube.com/watch?v=s0VcRAfXzLY&list=RDs0VcRAfXzLY&start_radio=1",
  "https://www.youtube.com/watch?v=hvaqFn5dvhU&list=RDhvaqFn5dvhU&start_radio=1",
  "https://www.youtube.com/watch?v=dvgZkm1xWPE&list=RDdvgZkm1xWPE&start_radio=1",
  
  // Marta santos
  "https://www.youtube.com/watch?v=E3DssUsnWEU",
  "https://www.youtube.com/watch?v=p3TzVLKY1RU&list=RDp3TzVLKY1RU&start_radio=1",
   "https://www.youtube.com/watch?v=snynIT2nV5c",
   "https://www.youtube.com/watch?v=qaYA35z0r1s&list=RDqaYA35z0r1s&start_radio=1",
   "https://www.youtube.com/watch?v=9ZMLSI-wFSE&list=RD9ZMLSI-wFSE&start_radio=1",
   "https://www.youtube.com/watch?v=iBhE1xMcmp0&list=RDiBhE1xMcmp0&start_radio=1",
  // 50 canciones para subir el ánimo al instante
  "https://www.youtube.com/watch?v=1dQ7yL0mTxQ",
  "https://www.youtube.com/watch?v=ZbZSe6N_BXs",
  "https://www.youtube.com/watch?v=gmj8HX0OmXc",
  "https://www.youtube.com/watch?v=U2N5V_Tz9mA",
  "https://www.youtube.com/watch?v=CevxZvSJLk8",
  "https://www.youtube.com/watch?v=09R8_2nJtjg",
  "https://www.youtube.com/watch?v=VbfpW0pbvaU",
  "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
  "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
  "https://www.youtube.com/watch?v=6Ejga4kJUts",
  "https://www.youtube.com/watch?v=3GwjfUFyY6M",
  "https://www.youtube.com/watch?v=fLexgOxsZu0",
  "https://www.youtube.com/watch?v=lWA2pjMjpBs",
  "https://www.youtube.com/watch?v=09R8_2nJtjg",
  "https://www.youtube.com/watch?v=uelHwf8o7_U",
  "https://www.youtube.com/watch?v=09t5T6JjUeE",
  "https://www.youtube.com/watch?v=PWgvGjAhvIw",
  "https://www.youtube.com/watch?v=RgKAFK5djSk",
  "https://www.youtube.com/watch?v=2vjPBrBU-TM",
  "https://www.youtube.com/watch?v=2X_2IdybTV0",
  "https://www.youtube.com/watch?v=l7Fd8-2llQI",
  "https://www.youtube.com/watch?v=4J6c2j71B84",
  "https://www.youtube.com/watch?v=9bZkp7q19f0",
  "https://www.youtube.com/watch?v=oRdxUFDoQe0",
  "https://www.youtube.com/watch?v=OPf0YbXqDm0",
  "https://www.youtube.com/watch?v=YQHsXMglC9A",
  "https://www.youtube.com/watch?v=hT_nvWreIhg",
  "https://www.youtube.com/watch?v=fRh_vgS2dFE",
  "https://www.youtube.com/watch?v=09R8_2nJtjg",
  "https://www.youtube.com/watch?v=VbfpW0pbvaU",
  "https://www.youtube.com/watch?v=09R8_2nJtjg",
  "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
  "https://www.youtube.com/watch?v=uelHwf8o7_U",
  "https://www.youtube.com/watch?v=RgKAFK5djSk",
  "https://www.youtube.com/watch?v=CevxZvSJLk8",
  "https://www.youtube.com/watch?v=NT0oM3b8xvQ",
  "https://www.youtube.com/watch?v=2X_2IdybTV0",
  "https://www.youtube.com/watch?v=fLexgOxsZu0",
  "https://www.youtube.com/watch?v=PWgvGjAhvIw",
  "https://www.youtube.com/watch?v=3GwjfUFyY6M",
  "https://www.youtube.com/watch?v=6Ejga4kJUts",
  "https://www.youtube.com/watch?v=lWA2pjMjpBs",
  "https://www.youtube.com/watch?v=60ItHLz5WEA",
  "https://www.youtube.com/watch?v=2Vv-BfVoq4g"
];

// ======== ARCHIVO PARA GUARDAR ESTADO DE CANCIONES ========
const estadoArchivo = './estado.json';
let estado = { cancionesEnviadas: [] };

// Cargar estado si existe
if (fs.existsSync(estadoArchivo)) {
  estado = JSON.parse(fs.readFileSync(estadoArchivo));
}

// ======== FUNCIONES AUXILIARES ========
function guardarEstado() {
  fs.writeFileSync(estadoArchivo, JSON.stringify(estado, null, 2));
}

function generarFrase(arreglo) {
  return arreglo[Math.floor(Math.random() * arreglo.length)];
}

function generarCancionUnica() {
  const disponibles = cancionesBuenosDias.filter(c => !estado.cancionesEnviadas.includes(c));
  if (disponibles.length === 0) {
    // Reiniciamos cuando se acaben
    estado.cancionesEnviadas = [];
    guardarEstado();
    return generarCancionUnica();
  }
  const cancion = disponibles[Math.floor(Math.random() * disponibles.length)];
  estado.cancionesEnviadas.push(cancion);
  guardarEstado();
  return cancion;
}

function enviarCancionYFrase(chatId) {
  const cancion = generarCancionUnica();
  bot.sendMessage(chatId, `¡Buenos días! Disfruta esta canción: ${cancion}`).then(() => {
    const frase = generarFrase(frasesBuenosDias);
    bot.sendMessage(chatId, `☀️ ${frase}`);
  });
}

// ======== ENVÍO DIARIO: CANCION + FRASE DE BUENOS DÍAS 08:00 ========
cron.schedule('0 8 * * *', () => {
  enviarCancionYFrase(chatId);
  console.log('Canción y frase de buenos días enviadas');
}, {
  timezone: "Europe/Dublin"
});

// ======== ENVÍO DIARIO: FRASE MOTIVADORA 15:55 ========
cron.schedule('55 15 * * *', () => {
  const frase = generarFrase(frasesMotivadoras);
  bot.sendMessage(chatId, frase + "\nYa has salido del trabajo mi amor? Animate que cuanto más trabajes, más dinero y ahora que has terminado tu jornada a descansar");
  console.log('Frase motivadora enviada:', frase);
}, {
  timezone: "Europe/Dublin"
});

// ======== ENVÍO DIARIO: BUENAS NOCHES 22:00 ========
cron.schedule('0 20 * * *', () => {
  const mensaje = generarFrase(frasesBuenasNoches); // Puedes crear otra lista de buenas noches si quieres
  bot.sendMessage(chatId, mensaje + "\nDescansaa😘❤️");
  console.log('Mensaje de buenas noches enviado:', mensaje);
}, {
  timezone: "Europe/Dublin"
});

// ======== COMANDO MANUAL /frase ========

bot.onText(/\/frase/, (msg) => {
  const frase = generarFrase(frasesMotivadoras);
  bot.sendMessage(msg.chat.id, frase);
  console.log('Frase enviada con /frase:', frase);
});
// ======== COMANDO MANUAL /cancion ========
bot.onText(/\/cancion/, (msg) => {
  const cancion = generarFrase(cancionesBuenosDias); // cancionesBuenosDias es tu array de canciones con enlaces
  bot.sendMessage(msg.chat.id, `Aquí tienes tu canción del día: \n${cancion}`);
  console.log('Canción enviada con /cancion:', cancion);
});
// ======== DETECCIÓN DE ESTADO DE ÁNIMO ========
const palabrasNegativas = ["mal", "estresada", "bajón", "bajona", "triste", "agotada", "cansada"];
const frasesAnimar = [
  "¡Ánimo! Todo pasa y siempre hay un motivo para sonreír 😊✨\nMás alegría con una sola llamada: 👇https://wa.me/34642297675 📞",
  "Respira hondo, relájate y recuerda que eres fuerte 💪🌸 \n Más alegría con una sola llamada: 👇https://wa.me/34642297675 📞",
  "Los días difíciles también enseñan cosas bonitas 🌈🌻\nMás alegría con una sola llamada: 👇https://wa.me/34642297675 📞",
  "Tómate un momento para ti, mereces cuidar de tu bienestar 🧘‍♀️💛\nMás alegría con una sola llamada: 👇https://wa.me/34642297675 📞",
  "Después de la tormenta siempre llega la calma 🌤️💖\nMás alegría con una sola llamada: 👇https://wa.me/34642297675 📞",
  "Si necesitas desconectar, pon tu canción favorita y sonríe 🎶😄\nMás alegría con una sola llamada: 👇https://wa.me/34642297675 📞",
  "Eso es porque no lo has probado bien 😂😂😂\nMás alegría con una sola llamada: 👇https://wa.me/34642297675 📞",
  "Lucy no comas solo lechuga, que te vas a parecer a mi tortuga 🐢",
  "Sabes que ha llegado el momento de que me llames 😄",
  "Solo recuerda que ya queda menos 🌻 \nMás alegría con una sola llamada: 👇https://wa.me/34642297675 📞"
];

bot.on('message', (msg) => {
  const texto = msg.text.toLowerCase();
  // Si alguna palabra negativa está en el mensaje
  
  if (palabrasNegativas.some(palabra => texto.includes(palabra))) {
    const mensajeAnimador = generarFrase(frasesAnimar);
    bot.sendMessage(msg.chat.id, mensajeAnimador, {disable_web_page_preview: true});
    console.log('Mensaje animador enviado:', mensajeAnimador);
  }
});

// ======== OBTENER CURIOSIDAD DEL DÍA ========
async function obtenerCuriosidad() {
  try {
    const res = await fetch('https://uselessfacts.jsph.pl/random.json?language=en');
    const data = await res.json();
    return data.text; // La curiosidad en inglés
  } catch (error) {
    console.error('Error al obtener curiosidad:', error);
    return "🧠 No se pudo obtener la curiosidad del día hoy, ¡intenta más tarde!";
  }
}

// ======== ENVÍO DIARIO: CURIOSIDAD DEL DÍA 12:00 ========
cron.schedule('11 21 * * *', async () => {
  const curiosidad = await obtenerCuriosidad();
  bot.sendMessage(chatId, `🧠 Curiosity of the Day:\n${curiosidad}`);
  console.log('Curiosidad del día enviada:', curiosidad);
}, {
  timezone: "Europe/Dublin"
});

// ======== COMANDO MANUAL /curiosidad ========
bot.onText(/\/curiosidad/, async (msg) => {
  const curiosidad = await obtenerCuriosidad();
  bot.sendMessage(msg.chat.id, `🧠 Curiosity:\n${curiosidad}`);
  console.log('Curiosidad enviada con /curiosidad:', curiosidad);
});

console.log('Bot avanzado iniciado y listo. 🌞🎵');
















